# Generated by Django 6.0.7 on 2026-07-22 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_globally_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled_for_users', models.ManyToManyField(blank=True, related_name='enabled_flags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
