# Generated by Django 6.0.7 on 2026-07-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_monitor_last_checked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='auth_credential_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='auth_header_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='monitor',
            name='auth_type',
            field=models.CharField(choices=[('NONE', 'None'), ('BASIC', 'HTTP Basic'), ('BEARER', 'Bearer token'), ('API_KEY', 'API key header')], default='NONE', max_length=10),
        ),
    ]
