# Generated by Django 6.0.7 on 2026-07-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='last_escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
