# Generated by Django 6.0.7 on 2026-07-22 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_up', models.BooleanField()),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('ssl_valid', models.BooleanField(blank=True, null=True)),
                ('ssl_expires_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitors.monitor')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['monitor', '-checked_at'], name='checks_chec_monitor_6ff031_idx')],
            },
        ),
    ]
